# Generated by Django 5.1.3 on 2024-12-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_watchhistory_watchlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
